### ISSUE TITLE
Deleting Producer/Consumer causes crash

### ISSUE THREAD

**Issue by bahar-p** [flightaware/kafkatcl#14]
Whenever I attempt to execute producer or consumer delete my shell crashes. 
As far as I remember, in the previous release this command used to work fine I guess. Not sure what's causing it now...

**Comment by bovine** [comment]
Does this still occur with the current release? If so, can you provide some sample code that replicates this?

**Comment by bovine** [comment]
Closing due to no response from @bahar-p
