### ISSUE TITLE
"meta" command is missing subcommands

### ISSUE THREAD

**Issue by mutability** [flightaware/kafkatcl#3]
(oops, too fast on the enter key)

```
$ tclsh
% package require kafka
1.1
% ::kafka::consumer_setup -brokers hekri
invalid command name "::kafka::consumer_setup"
% ::kafka::setup_consumer -brokers hekri
% ::kafka::consumer meta refresh
wrong # args: should be "::kafka::consumer meta "
% ::kafka::consumer meta
```

Docs say there should be refresh & print, and indeed the code is there for them, but a bit mangled so you effectively always get a refresh and can't specify a subcommand properly.

**Comment by lehenbauer** [comment]
Fixed by https://github.com/flightaware/kafkatcl/commit/d7d190457c305990d055185d41826bf273786957
