### ISSUE TITLE
delivery reports do not appear to work

### ISSUE THREAD

**Issue by mutability** [flightaware/kafkatcl#4]
I can't get delivery reports to fire at all. If I produce a message and wait for a delivery callback, the message is produced OK but the callback is never invoked.

See https://gist.github.com/mutability/83b5f59566eb3a73356f for a test script.

**Comment by lehenbauer** [comment]
The delivery report callback settings are inherited when a producer is created.  After your script has invoked ::kafka::setup_producer to create a producer, delivery report changes to the master object won't be inherited.

If you'll add a kafka::setup and move the call to kafka::setup_producer to be after the callback setup, it will work.

```
diff --git a/produce.tcl b/produce.tcl
index 7e2b71e..e08ab56 100644
--- a/produce.tcl
+++ b/produce.tcl
@@ -10,12 +10,15 @@ proc the_error_callback {message} {
        set ::die 1
 }

-::kafka::setup_producer -brokers hekri
+kafka::setup
+
 ::kafka::master delivery_report callback the_delivery_callback
 ::kafka::master delivery_report every 1
 ::kafka::master error_callback the_error_callback
 ::kafka::master logger stderr

+::kafka::setup_producer -brokers hekri
+
 ::kafka::producer config request.required.acks 1
 ::kafka::producer config request.timeout.ms 5000
 ::kafka::producer config message.timeout.ms 10000
```

**Comment by lehenbauer** [comment]
Updated the docs at https://github.com/flightaware/kafkatcl/commit/0997692af0e5ac0453325c70da4ab39ffcf47335 but I'm still not completely happy with how the easy-way stuff works.

**Comment by mutability** [comment]
I think it's going to be common to want a different delivery callback for different topics. Having to reconfigure the master and then create a producer-creator separately for each topic is a bit cumbersome.

**Comment by mutability** [comment]
delivery reports work fine now
