### ISSUE TITLE
add_brokers doesn't work if given a tcl list

### ISSUE THREAD

**Issue by mutability** [flightaware/kafkatcl#5]
rdkafka expects a comma-separated list of brokers, but kafkatcl doesn't do anything to transform from a tcl list to that form.

**Comment by lehenbauer** [comment]
You're right.  We will adapt kafkatcl to accept a Tcl list and do the right thing, transforming it to comma-separated behind your back.

**Comment by lehenbauer** [comment]
Fixed by commit 26c70824a2785a91398b34a63b3fcaa9b02f9d1b.
